/*
 * CharStats.java
 *
 * Created on July 7, 2003, 7:55 PM
 */

package IsometricGame.Client;

import IsometricGame.Entity.*;

/**
 *
 * @author  jgauci
 */
public class PlayerStatsPanel extends javax.swing.JPanel {
    
    /** Creates new form CharStats */
    public PlayerStatsPanel() {
        initComponents();
    }
    
    public void update(Avatar tempAvatar) {
        if(tempAvatar==null) {
            agiLabel.setText("");
            levelLabel.setText("");
            dexLabel.setText("");
            mrkLabel.setText("");
            strLabel.setText("");
            expLabel.setText("");
            ldrLabel.setText("");
            mecLabel.setText("");
            wisLabel.setText("");
            medLabel.setText("");
            healthBar.setMaximum(1);
            healthBar.setValue(0);
            staminaBar.setMaximum(1);
            staminaBar.setValue(0);
            energyBar.setMaximum(1);
            energyBar.setValue(0);
        }
        else {
         /*   agiLabel.setText(""+tempAvatar.agility);
            levelLabel.setText(""+tempAvatar.level);
            dexLabel.setText(""+tempAvatar.dexterity);
            mrkLabel.setText(""+tempAvatar.marksmanship);
            strLabel.setText(""+tempAvatar.strength);
            expLabel.setText(""+tempAvatar.explosives);
            ldrLabel.setText(""+tempAvatar.leadership);
            mecLabel.setText(""+tempAvatar.mechanical);
            wisLabel.setText(""+tempAvatar.wisdom);
            medLabel.setText(""+tempAvatar.medicine);*/
            healthBar.setMaximum(tempAvatar.maxHealth);
            healthBar.setValue(tempAvatar.health);
            staminaBar.setMaximum(tempAvatar.maxStamina);
            staminaBar.setValue(tempAvatar.stamina);
            energyBar.setMaximum(tempAvatar.maxEnergy);
            energyBar.setValue(tempAvatar.energy);
        }
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        healthBar = new javax.swing.JProgressBar();
        staminaBar = new javax.swing.JProgressBar();
        energyBar = new javax.swing.JProgressBar();
        stats = new javax.swing.JPanel();
        AGI = new javax.swing.JLabel();
        agiLabel = new javax.swing.JLabel();
        LVL = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        DEX = new javax.swing.JLabel();
        dexLabel = new javax.swing.JLabel();
        MRK = new javax.swing.JLabel();
        mrkLabel = new javax.swing.JLabel();
        STR = new javax.swing.JLabel();
        strLabel = new javax.swing.JLabel();
        EXP = new javax.swing.JLabel();
        expLabel = new javax.swing.JLabel();
        LDR = new javax.swing.JLabel();
        ldrLabel = new javax.swing.JLabel();
        MEC = new javax.swing.JLabel();
        mecLabel = new javax.swing.JLabel();
        WIS = new javax.swing.JLabel();
        wisLabel = new javax.swing.JLabel();
        MED = new javax.swing.JLabel();
        medLabel = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        healthBar.setForeground(new java.awt.Color(255, 0, 0));
        healthBar.setToolTipText("Health");
        healthBar.setMaximumSize(new java.awt.Dimension(32767, 5));
        healthBar.setMinimumSize(new java.awt.Dimension(10, 5));
        healthBar.setPreferredSize(new java.awt.Dimension(148, 10));
        add(healthBar);

        staminaBar.setForeground(new java.awt.Color(0, 153, 0));
        staminaBar.setToolTipText("Stamina");
        staminaBar.setMaximumSize(new java.awt.Dimension(32767, 5));
        staminaBar.setMinimumSize(new java.awt.Dimension(10, 5));
        staminaBar.setPreferredSize(new java.awt.Dimension(148, 10));
        add(staminaBar);

        add(energyBar);

        stats.setLayout(new java.awt.GridLayout(5, 4, 1, 0));

        AGI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AGI.setText("AGI");
        AGI.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        stats.add(AGI);

        agiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stats.add(agiLabel);

        LVL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LVL.setText("LVL");
        LVL.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        stats.add(LVL);

        levelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stats.add(levelLabel);

        DEX.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DEX.setText("DEX");
        stats.add(DEX);

        dexLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stats.add(dexLabel);

        MRK.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MRK.setText("MRK");
        stats.add(MRK);

        mrkLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stats.add(mrkLabel);

        STR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        STR.setText("STR");
        STR.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        stats.add(STR);

        strLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stats.add(strLabel);

        EXP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EXP.setText("EXP");
        stats.add(EXP);

        expLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stats.add(expLabel);

        LDR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LDR.setText("LDR");
        stats.add(LDR);

        ldrLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stats.add(ldrLabel);

        MEC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MEC.setText("MEC");
        stats.add(MEC);

        mecLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stats.add(mecLabel);

        WIS.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        WIS.setText("WIS");
        stats.add(WIS);

        wisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stats.add(wisLabel);

        MED.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MED.setText("MED");
        stats.add(MED);

        medLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stats.add(medLabel);

        add(stats);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AGI;
    private javax.swing.JLabel DEX;
    private javax.swing.JLabel EXP;
    private javax.swing.JLabel LDR;
    private javax.swing.JLabel LVL;
    private javax.swing.JLabel MEC;
    private javax.swing.JLabel MED;
    private javax.swing.JLabel MRK;
    private javax.swing.JLabel STR;
    private javax.swing.JLabel WIS;
    private javax.swing.JLabel agiLabel;
    private javax.swing.JLabel dexLabel;
    private javax.swing.JProgressBar energyBar;
    private javax.swing.JLabel expLabel;
    private javax.swing.JProgressBar healthBar;
    private javax.swing.JLabel ldrLabel;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel mecLabel;
    private javax.swing.JLabel medLabel;
    private javax.swing.JLabel mrkLabel;
    private javax.swing.JProgressBar staminaBar;
    private javax.swing.JPanel stats;
    private javax.swing.JLabel strLabel;
    private javax.swing.JLabel wisLabel;
    // End of variables declaration//GEN-END:variables
    
}
