/*
 * PlayerInventoryPanel.java
 *
 * Created on August 13, 2003, 12:28 PM
 */

package IsometricGame.Client;

import IsometricGame.Entity.*;
import IsometricGame.Item.*;

import java.util.*;

/**
 *
 * @author  jgauci
 */
public class PlayerInventoryPanel extends javax.swing.JPanel {
    GroundPanel ground;
    InventoryPanel inventory;
    GameClient owner;
    
    /** Creates new form PlayerInventoryPanel */
    public PlayerInventoryPanel(GameClient client) {
        this.owner = client;
        initComponents();
        ground = new GroundPanel(this);
        jScrollPane2.setViewportView(ground);
    }
    
    public void update() {
        ground.update();
        inventory.update();
    }
    
    public void setGroundScroll()
    {
        jScrollPane2.setViewportView(ground);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   private void initComponents() {//GEN-BEGIN:initComponents
      jPanel2 = inventory = new InventoryPanel(this);
      jScrollPane2 = new javax.swing.JScrollPane();

      setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

      jPanel2.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
      jPanel2.setMaximumSize(new java.awt.Dimension(300, 200));
      jPanel2.setMinimumSize(new java.awt.Dimension(300, 200));
      jPanel2.setPreferredSize(new java.awt.Dimension(300, 200));
      add(jPanel2);

      jScrollPane2.setViewportBorder(new javax.swing.border.MatteBorder(new java.awt.Insets(10, 10, 10, 10), new java.awt.Color(0, 0, 0)));
      add(jScrollPane2);

   }//GEN-END:initComponents
        
    
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane2;
   // End of variables declaration//GEN-END:variables
    
}
