//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Association.java
//  @ Date : 9/3/2007
//  @ Author : 
//
//




public class Association {
}
