//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Compostion.java
//  @ Date : 9/3/2007
//  @ Author : 
//
//




public class Compostion {
}
