//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DirectAssociation2.java
//  @ Date : 9/3/2007
//  @ Author : 
//
//




public class DirectAssociation2 {
}
