//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Realization2.java
//  @ Date : 9/3/2007
//  @ Author : 
//
//




public class Realization2 {
}
